### ISSUE TITLE
Create public image

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/golang-test-image#1]
@Mokto Could you create public image https://github.com/sentry-kubernetes/golang-test-image/pkgs/container/golang-test-image?

**Comment by Mokto** [comment]
Pushed `ghcr.io/sentry-kubernetes/golang-test-image:1.1.0` and made it public.

**Comment by patsevanton** [comment]
manually or does it automatically upload the image?

**Comment by Mokto** [comment]
Manually
